<% attributes = '
      certificate_services:
        standalone_root_ca:
          cdp_url: http://pki.contoso.com/cdp/%3%8.crl
          windows_domain: contoso.com
          policy:
            LegalPolicy:
              notice: Legal Policy Statement
              oid: 1.2.3.4.1455.67.89.5
              url: http://pki.contoso.com/cps/legal.txt
        enterprise_subordinate_ca:
          aia_url: http://pki.contoso.com/cdp/%3%4.crt
          cdp_url: http://pki.contoso.com/cdp/%3%8%9.crl
          domain_user: Administrator
          domain_pass: Passw0rd!
          install_cert: SUBCA.contoso.com_SUBCA-Issuing-CA.crt
          ocsp_url: http://pki.contoso.com/ocsp
          policy:
            LegalPolicy:
              notice: Legal Policy Statement
              oid: 1.2.3.4.1455.67.89.5
              url: http://pki.contoso.com/cps/legal.txt
          root_crl_file: ROOTCA-CA.crl
          root_crt_file: ROOTCA_ROOTCA-CA.crt
' %>
---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  root_path: /tmp/verifier

platforms:
  - name: windows2012r2
    driver:
      box: windows2012r2
      box_check_update: false
      box_url: https://artifacts.schubergphilis.com/artifacts/vagrant/sbp_windows_2012_r2_20141211_1.box

suites:
  - name: DomainController
    driver:
      network:
      - ["private_network", {ip: "192.168.33.10"}]
    run_list:
      - recipe[certificate_services_test::default]
      - recipe[certificate_services_test::domain_create]

  - name: StandaloneRootCA
    driver:
      vm_hostname: ROOTCA
      network:
      - ["private_network", {ip: "192.168.33.11"}]
    run_list:
      - recipe[certificate_services_test::default]
      - recipe[certificate_services::standalone_root_ca]
    attributes:
      <%= attributes %>

  - name: SubordinateCA
    driver:
      vm_hostname: SUBCA
      network:
      - ["private_network", {ip: "192.168.33.12"}]
    run_list:
      - recipe[certificate_services_test::default]
      - recipe[certificate_services_test::domain_join]
      - recipe[certificate_services::enterprise_subordinate_ca]
    attributes:
      <%= attributes %>

  - name: Web
    driver:
      vm_hostname: WEB
      network:
      - ["private_network", {ip: "192.168.33.13"}]
    run_list:
      - recipe[certificate_services_test::default]
      - recipe[certificate_services_test::domain_join]
      - recipe[certificate_services::crl_distribution_point]
    attributes:
      <%= attributes %>
