AllCops:
  Include:
    - 'Berksfile'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'Thorfile'
  Exclude:
    - 'vendor/**'

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/SingleSpaceBeforeFirstArg:
  Exclude:
    - '**/metadata.rb'
