name             'certificate_services'
maintainer       'Stephen Hoekstra'
maintainer_email 'shoekstra@schubergphilis.com'
license          'All rights reserved'
description      'Cookbook to install and configure Active Directory Certificate Services'
version          '0.1.0'
recipe           'certificate_services::_nrpe', 'Installs and configures NRPE scripts and checks for Nagios monitoring if the `nrpe` cookbook is included earlier in the run-list.'
recipe           'certificate_services::_selinux', 'Configures required SELinux settings if certificate_services is installed on an SELinux enabled system.'
recipe           'certificate_services::default', 'Installs and configures the application.'
